# Generated by Django 3.2.6 on 2024-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uv_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weather_description', models.CharField(max_length=100)),
                ('weather_image', models.CharField(max_length=100)),
            ],
        ),
    ]
